apiVersion: apps/v1
kind: Deployment
metadata:
  name: project8-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project8
  template:
    metadata:
      labels:
        app: project8
    spec:
      containers:
      - name: project8-container
        image: dilip122390/project8-webapp:v1
        ports:
        - containerPort: 80
